### ISSUE TITLE
PDF problems

### ISSUE THREAD

**Issue by jkgrain** [rstudio/tufte#10]
I have a pretty simple Rmd that generates a bunch of figures, each in its own section. The figures are not showing up inside the correct sections starting with the 5th section and the subtitle doesn't appear at all in the document.  I am knitting the document by pressing the knit button in RStudio.  Here is a simple example that reproduces the issues:
<pre>
---
title: "This is The Title"
subtitle: "Subtitle"
author: "JKGrain"
date: "`r Sys.Date()`"
output:
  tufte::tufte_handout: default

---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'), echo=FALSE)
options(htmltools.dir.version = FALSE)

# load required libaries
library(ggplot2)
p1 <- ggplot(mpg) +
  geom_point(aes(x=displ, y=hwy, color=cyl))

```

# Section 1

```{r sec1, fig.cap = "The first caption"}
p1
```

# Section 2

```{r sec2, fig.cap = "The second caption"}
p1
```

# Section 3

```{r sec3, fig.cap = "The third caption"}
p1 
```

# Section 4

```{r sec4, fig.cap = "The fourth caption"}
p1 
```

# Section 5

```{r sec5, fig.cap = "The fifth caption"}
p1
```

# Section 6

```{r sec6, fig.cap = "The sixth caption"}
p1
```

# Section 7

```{r sec7, fig.cap = "The seventh caption"}
p1
```

# Section 8

```{r sec8, fig.cap = "The eighth caption"}
p1
```
</pre>

when I change the YAML to:
<pre>tufte::tufte_html: default</pre>
and press the knit button in Rstudio, the html renders correctly with the figures all in the correct sections and the subtitle.  The PDF output is pretty useless though at this point.  I have to email the report and I can't use the html version.

Thanks for looking at this.

**Comment by yihui** [comment]
1. The tufte-latex class does not support subtitles;
2. Welcome to the LaTeX world -- figures and tables float in this world :)
