### ISSUE TITLE
Tufte pdf documents fail to compile with `vadjust` error

### ISSUE THREAD

**Issue by rmcd1024** [rstudio/tufte#106]
Compiling the below document succeeds for `pdf_document` and fails for all of the tufte pdf formats with the error 

```
! You can't use `\vadjust' in vertical mode.
l.189 \leavevmode\vadjust
                          pre{\hypertarget{ref-grolemundux2fwickham:17}{}}% 
```

````
---
output:
  pdf_document: default
  tufte::tufte_handout: default
bibliography: outputformat2.bib
---

@grolemund/wickham:17

```{r}
sessioninfo::session_info()
```
````

Successful compile including `session_info` output: [testtufte.pdf](https://github.com/rstudio/tufte/files/7728483/testtufte.pdf)
Bib file: [outputformat2.zip](https://github.com/rstudio/tufte/files/7728493/outputformat2.zip)

Update: I've verified that this happens also with pandoc 2.14.2.

**Comment by cderv** [comment]
Thanks for the report.

I think it was related to https://github.com/jgm/pandoc/issues/7215 and an update to Pandoc template was necessary. 

This should now work ok in dev version of the package. 

```r
remotes::install_github("rstudio/tufte")
```

Thanks!
