### ISSUE TITLE
Broken citation formats in html

### ISSUE THREAD

**Issue by TomBener** [rstudio/tufte#115]
On 2022-06-15, I cloned the repo and knit `skeleton.Rmd` to html. However, It looks weird. In the following screenshot, texts following the citation `[@R-base]` were rendered as italic, and the reference in the sidenote was not correct. In the [example page](https://rstudio.github.io/tufte/), It is “R Core Team. 2021. _R: A Language and Environment for Statistical Computing_. Vienna, Austria: R Foundation for Statistical Computing. https://www.r-project.org/.”

<img width="1264" alt="CleanShot 2022-06-15 at 16 05 35@2x" src="https://user-images.githubusercontent.com/49151155/173777371-b5ddcc5d-8dce-4289-8106-2408411141bd.png">
 
Some information on my test:

- OS: macOS 12.4
- Pandoc version: 2.18
- R: 4.2.0
- rmarkdown: 2.14

Furthermore, I create a new `.Rmd` file. And it encountered similar issues. Some references did not appear on the right side, and a few bibliographies were split arbitrarily. In addition, some texts were hyperlinked incorrectly.

<img width="1269" alt="CleanShot 2022-06-15 at 16 28 46@2x" src="https://user-images.githubusercontent.com/49151155/173781357-f0de9027-1dbf-489d-a1a7-4c818e5ef3f8.png">

I’m not sure if the package has any bug. Could you please help with this?

By the way, [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) seems to be deprecated, but the manual page mentioned that `pandoc-citeproc should be at least 0.7.2`. Please update it. Thanks.

**Comment by cderv** [comment]
Thanks for the report. I believe this is linked to https://github.com/rstudio/rmarkdown/issues/2369 and I think I need to fix it in **rmarkdown**

To confirm this is the issue, you can do this 
```yaml
output:
  tufte::tufte_html: 
    pandoc_args: '--wrap=none'
````

This should make everything right. 

> By the way, [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) seems to be deprecated, but the manual page mentioned that pandoc-citeproc should be at least 0.7.2. Please update it. Thanks.

I added mention of Pandoc 2.11 and above. i'll update the doc once I fixed in **rmarkdown**

**Comment by TomBener** [comment]
> ```yaml
> output:
>   tufte::tufte_html: 
>     pandoc_args: '--wrap=none'
> ```

Thanks, it works well!

**Comment by cderv** [comment]
Good. That means it is the issue. I need to add this internally so that a user doesn't have to set it. 

For the context, this is due to a Pandoc change that modify the default for this behavior so we need to adjust. Getting back to an older Pandoc is also a workaround.
