### ISSUE TITLE
Register tufte engines in .onLoad()?

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/tufte#117]
Hi all,

We are working on an issue in {lintr} whereby tufte's specific engines are not recognized and thus cause spurious lints / syntax issues: https://github.com/r-lib/lintr/issues/796

We'd like to avoid a solution where we hard-code some information specific to {tufte}, which opens a pandora's box for us to maintain this information not only for {tufte}, but any other engine-generating {knitr} downstreams as well.

The solution we've landed on for {bookdown} is pretty simple -- we need only run `loadNamespace("bookdown")` and _voila_! we can use `knitr::knit_engines$get()` to tell us what engines are registered. See https://github.com/r-lib/lintr/pull/1552/files/94c50f355a53c2d50e0fd8f1be1f99d51531e297

That's because {bookdown} is registering its engines in its `.onLoad()` hook:

https://github.com/rstudio/bookdown/blob/7b53f2dd7ddb57b7e78ee1575c06b892f549c4e8/R/zzz.R#L4-L6
https://github.com/rstudio/bookdown/blob/7b53f2dd7ddb57b7e78ee1575c06b892f549c4e8/R/utils.R#L589-L594

Is there any disadvantage to doing something similar for the engines {tufte} provides?

**Comment by yihui** [comment]
We registered the `marginfigure` engine in different output format functions because it behaves differently for different output formats. We could definitely register it in `.onLoad()` and overwrite it inside output format functions. That should be harmless to this package.

**Comment by MichaelChirico** [comment]
Oh that makes sense, thanks for clarifying.

So adding a registration in .onLoad in this case is kind of like a virtual class declaration? the "class" of engine is declared but the implementation is left to "subclasses", is that a good way to describe it?

**Comment by yihui** [comment]
Yes.
