### ISSUE TITLE
Percent sign in margin note

### ISSUE THREAD

**Issue by hobrien** [rstudio/tufte#12]
Thanks for this package. Looks fantastic. 

I've encountered a problem with percent signs in the margin_note() function. It works fine when I knit as html, but it's causing pandoc to choke when I knit as pdf. I assume it's being passed to pandoc unescaped, but if I use \%, then R chokes on it. Any suggestions?

**Comment by yihui** [comment]
I think you need double backslashes in this case. In a character string in R, double backslashes mean a literal backslash.

**Comment by hobrien** [comment]
That works! Should of guessed that the solution would be more backslashes. Thanks!
