### ISSUE TITLE
[tufte_html] Small width of code blocks when highlight is not default

### ISSUE THREAD

**Issue by mr-majkel** [rstudio/tufte#15]
Hi,

first of all let me thank you for the great package.

I have noticed that when in YAML I select some other highlighting of the code than the default (e.g. set to tango), the code blocks get shrunk. Is there any workaround for this behavior?

Best regards,
Michal

**Comment by yihui** [comment]
This is indeed a bug, but I don't have time to figure out a solution at the moment. If you know how to fix it, a pull request will be much appreciated! (It should not be super difficult; I think it is just a CSS problem)

**Comment by cderv** [comment]
I do not manage to reproduce this. Is this still an issue ?
It is an very old issue so it is possible this has been fixed.

**Comment by yihui** [comment]
I don't know. I'll close it for now. Thanks!
