### ISSUE TITLE
Template files missing

### ISSUE THREAD

**Issue by abarbour** [rstudio/tufte#16]
The example on http://rmarkdown.rstudio.com/tufte_handout_format.html fails because of missing template file(s):

```
> draft("my_handout.Rmd", template = "tufte_handout", package = "tufte")
Error in draft("my_handout.Rmd", template = "tufte_handout", package = "tufte") :
  No template.yaml file found for template 'tufte_handout'
```

**Comment by jjallaire** [comment]
Thanks, fixed here: https://github.com/rstudio/rmarkdown/commit/5c5cdcd5c337166f043a3861e11fa58085d66a67
