### ISSUE TITLE
ebook

### ISSUE THREAD

**Issue by elbamos** [rstudio/tufte#2]
@yihui This looks great!  

I think the ebook class would fit right in.  

I could just make the PR, but perhaps the easiest first step would be for you to take a look at it and see if there's anything you'd like me to modify first. 

Regarding the comment from @jjallaire about minimal TeX distributions, I don't have any opinion.  I included what files seemed to best conform with the way the other template packages were organized.  I think there were a few changes to the original class files but not a huge number of them.

**Comment by yihui** [comment]
@elbamos You can put together the PR and we can discuss from there.

@jjallaire FWIW, I don't think tufte-handout.cls or tufte-common.def are copied by `draft()`: https://github.com/rstudio/rmarkdown/tree/master/inst/rmarkdown/templates/tufte_handout/resources and we do not seem to have seen problems with that, so it is either that there are not many people using tufte_handout(), or they all know how to install the tufte-latex package. Either way, I guess it is not a big problem, and we can try to go ahead without tufte-handout.cls/.def in this package. If it does become an issue in the future, we can add them back.

**Comment by jjallaire** [comment]
Okay, we can leave them out, but before we promote the package widely (e.g.
on our blog) we should do some testing to see whether they are commonly
available in default configurations. If there's a way to probe for them I
guess we could also include them in RStudio and only make them available if
they aren't already on the system.

**Comment by yihui** [comment]
SInce this is not an issue specific to the Tufte LaTeX class, I guess we can solve it in a more general fashion, e.g. we can add an attribute to the output format and specify the LaTeX packages required. If any packages are missing, we can print out the instructions to install these packages.

**Comment by jjallaire** [comment]
That's an excellent idea!
