### ISSUE TITLE
Add tint as a sans-serif tufte layout option 

### ISSUE THREAD

**Issue by benmarwick** [rstudio/tufte#21]
There is a very nice sans-serif adaptation of this tufte template in the [`tint`](https://github.com/eddelbuettel/tint) package by @eddelbuettel. I wonder if that template could be added to this package? 

It would be great to have an easy sans-serif tufte template for bookdown, too. Perhaps tint would be suitable for that? The current tufte html output for bookdown is the least pleasant of all the bookdown output options (on my screen at least), with the yellow background and big black navigation buttons at the top).

**Comment by eddelbuettel** [comment]
Thanks, Ben. I had already emailed several times with JJ and Yihui, and only released/announced tint  when Yihui indicated he was temporarily busy -- we are all on the same page.  I am still quite hopeful tint will end up here, at least for html, provided we find some time to do it.

**Comment by yihui** [comment]
I have made the default fonts, the background color, and italic headers optional. You can choose which features to enable in the default Tufte style. I didn't really study what Dirk did in tint carefully (it would be much easier to know the exact changes if this started as a pull request or a new git branch; all I did was in ed6ed378c61ec8f51b5e97f9e9fe0b64d9c86394), so I don't know if I have provided all features you want via `tufte_html(tufte_variant = 'envisioned')`. See the last section here: http://rstudio.github.io/tufte/envisioned/

@benmarwick RE: bookdown our primary support is obviously on the Gitbook style. A Tufte example is here: https://bookdown.org/yihui/bookdown-demo3/ There is certainly more work to do, but I have ran out of time. Anyway, you do have all the freedom to customize the style by using CSS, so if you really love the Tufte style, please help us improve it in bookdown (in other words, pull requests welcome). The key thing I haven't quite got right is the navigation menu. I really don't know what a good design could be in this case. The bottom buttons are easy enough to style.

**Comment by eddelbuettel** [comment]
Did you support pdf as well?  I have that mostly ready to commit on my laptop.

**Comment by benmarwick** [comment]
Thanks very much for adding this!

**Comment by yihui** [comment]
@eddelbuettel What do you mean by "support pdf"? The PDF support was there from day one as the output formats `tufte::tufte_handout` and `tufte::tufte_book`.

**Comment by eddelbuettel** [comment]
@yihui pdf output using RobotoCondensed, no italics, ... similar to what _tufte envisioned_ and _tint_ do in html.  I have something for that now.  I only looked at supporting tufte-handout, not tufte-book.

**Comment by yihui** [comment]
Just like for HTML output, you always have the `css` option for customizing the styles. For LaTeX output, you have the `includes` option, e.g. you can define the fonts in `preamble.tex` 

```latex
% if you use xelatex
\setmainfont{Roboto Condensed}
```

and set the output format option

```yaml
---
output:
  tufte::tufte_handout:
    includes:
      in_header: preamble.tex
---
```

R Markdown is very customizable and extensible. If there is anything hardcoded in rmarkdown/tufte that prevents you from customizing the output, we can certainly consider removing these constraints, but so far I have not seen such things in your cases.

**Comment by eddelbuettel** [comment]
Point takem and I am aware of that as I have been doing for a few years for (heavily customized) beamer presentations from markdown, following some initial help from JJ.  

I have some GH repos with style and fonts support, mostly delivered as .deb packages suiting my deployments. There was [one blog post](http://dirk.eddelbuettel.com/blog/2016/06/30/), written mostly in a rushed break at useR, when someone prompted me to allow some peeks behind the curtain.

Here, I am going a different route as I wanted to explore templates for rmarkdown.  Which tint now does in the way I wanted it to work, so we may as well end here.
