### ISSUE TITLE
section_numbers ignored in handout

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/tufte#23]
Adding the yaml header `number_sections` works in html mode, for pdf handout it does not work.

The numbered sections appear in the toc though (if that option is set).

The command-line call to pandoc shows it, though, so it may well be the latex class not supporting it.  In that case ... should the top-level argument be ignored / trigger a warning in `tufte_handout()` ?  The disconnect between table of contents and actual sections is a little weird.

**Comment by yihui** [comment]
I added `toc: yes` and `number_sections: yes` to the default example `skeleton.Rmd`, and the output is below (sections are numbered in both TOC and actual headers):

![image](https://cloud.githubusercontent.com/assets/163582/19288116/2b19d8a0-8fca-11e6-822d-063d187d4f2a.png)

**Comment by eddelbuettel** [comment]
Weird.  That is what I did too (modulo `TRUE` vs `yes`).

I have `packageVersion("tufte")` as 0.2, on Ubuntu 16.04 and do *not* get numbered sections.

The file tufte-handout.cls is 2015/06/21 v3.52. per its header.  What do you have?

**Comment by yihui** [comment]
Same versions of the tufte package and tufte-handout.cls.

```
> packageVersion('tufte')
[1] ‘0.2’

> system('head `kpsewhich tufte-handout.cls`')
\NeedsTeXFormat{LaTeX2e}[1994/06/01]

\ProvidesClass{tufte-handout}[2015/06/21 v3.5.2 Tufte-handout class]

%%
% Declare we're tufte-handout
\newcommand{\@tufte@class}{article}% the base LaTeX class (defaults to the article/handout style)
\newcommand{\@tufte@pkgname}{tufte-handout}% the name of the package (defaults to tufte-handout)
```

You can add `keep_tex: yes` and examine the .tex file. It should contain this line:

```latex
\setcounter{secnumdepth}{2}
```

**Comment by eddelbuettel** [comment]
![screenshot from 2016-10-11 16-27-23](https://cloud.githubusercontent.com/assets/673121/19289326/cf8df934-8fcf-11e6-933e-fecb11192f65.png)

I'll poke around -- ball in my court.  This should work, and I double check on another machine.

For reference, screenshot included above.

**Comment by eddelbuettel** [comment]
Same on another machine with 16.04.  I suspect it is something on the Ubuntu side of things.  I do have 

```tex
\setcounter{secnumdepth}{2}
```

as we would guess from the toc shown, and `\section{}` commands as opposed to `\section*{}`.  Strange.
