### ISSUE TITLE
click-to-zoom functionality for margin figures (HTML)

### ISSUE THREAD

**Issue by dylanbeaudette** [rstudio/tufte#30]
First off, this is an excellent implementation of Tufte's elegant approach to page layout. Thank you.

I really like the idea of margin figures, however, they are often too small to read. A simple "click-to-zoom" functionality would be really handy. I suppose that this can be done with a little bit of CSS/JS magic.

I have found [this post](http://stackoverflow.com/questions/40401680/how-to-zoom-in-on-plots-inside-an-rmarkdown-presentation) that could possible be adapted for use in a standard .Rmd vs. "ioslides_presentation". Tinkering around resulted in nothing useful.

Thanks.

**Comment by yihui** [comment]
I think the SO answer you mentioned can be adapted to solve your problem, but I don't have time for now. Another more advanced library you can consider is fancybox: http://fancyapps.com/fancybox/ Of course you need to understand JavaScript...

**Comment by dylanbeaudette** [comment]
Thank you Yihui for your suggestions. I haven't the JS skill to implement anything other than a hack. Fancy box does seem like a nice candidate for this kind of functionality. On a related note, [knitrBootstrap](https://github.com/jimhester/knitrBootstrap) contains the functionality, but not the Tufte-esqe style that I am looking for.

Apart from a nasty hack, what could I do to get the click-to-zoom (e.g. fancybox) functionality into the tufte package? The first couple steps seem simple:

1. load jQuery and fancybox JS libraries at the top of the .Rmd document (does rmarkdown automatically include jQuery?)

2. init the fancybox functionality:

'''
$(document).ready(function() {
	$(".fancybox").fancybox({
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});
'''

3.. wrap images into anchor tags like this:

'''html
<a class="fancybox" rel="gallery1" href="image.jpg" title="fig.caption">
	<img src="image.jpg" alt="" />
</a>
'''

This might require some additional chunk options, e.g. to access the "rel" element, and a bit of extra text manipulation when chunks are converted into HTML.

Any suggestions?

**Comment by yihui** [comment]
I recommend you to ask this question on StackOverflow with tags `r`, `tufte`, `javascript`, `fancybox` instead of waiting for me schedule to clear up to help you. Thanks!
