### ISSUE TITLE
horizontal lines do not render properly in firefox?

### ISSUE THREAD

**Issue by ajdamico** [rstudio/tufte#32]
screenshot with easy to reproduce example..  thanks!

![20161220 horizontal rule bisects footnotes in firefox](https://cloud.githubusercontent.com/assets/216807/21342769/ab2cf89c-c661-11e6-9bc9-1e7277dc979c.png)

**Comment by ajdamico** [comment]
thanks :)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
