### ISSUE TITLE
Full-width text blocks

### ISSUE THREAD

**Issue by mlovelace** [rstudio/tufte#33]
I love using the tufte_handout theme in RMarkdown. At times, I want to use the full width of the page for the main text. Is there a full-width text block feature similar to the full-width figure feature? If not, are there YAML or knitr options I could change to make the main text full width?

**Comment by yihui** [comment]
No, this is currently not supported.

**Comment by josiekre** [comment]
If you are not opposed to sprinkling in a little latex, you can simply do the following:

    \begin{fullwidth}
    This is text that will span full width.
    \end{fullwidth}

**Comment by kuochang** [comment]
It works!

**Comment by mlovelace** [comment]
Yep! A great solution. Thanks @josiekre! Unless I'm missing something, though, I think it only applies to pdf output. I haven't found a solution for html output that is just as quick as this one.

**Comment by yihui** [comment]
It is supported now, and works for both PDF and HTML output. Please see the documentation: https://rstudio.github.io/tufte/#arbitrary-full-width-content Thanks!

**Comment by mlovelace** [comment]
Thank you so much for adding this feature, @yihui! This is great news. So happy to hear that I can now easily add a full-width block for text to html docs. Thanks, again!
