### ISSUE TITLE
Wrap long lines in tufte_html sidemargin?

### ISSUE THREAD

**Issue by mbacou** [rstudio/tufte#36]
I have a few citations that include very long URLs (see pic) that do not wrap in the side margin. Might need an extra CCS rule `word-wrap: break-word;`.

![image](https://cloud.githubusercontent.com/assets/260325/24592731/7ebf3df4-17e9-11e7-9f15-f647d1e3704f.png)

**Comment by yihui** [comment]
I'm not sure if this should be included in the default CSS, but you can certainly add it to your custom CSS file.

**Comment by mbacou** [comment]
Right, I just did that in a custom CSS. Does not seem to have any negative side effect.
