### ISSUE TITLE
Table captions do not show in margin when compiling to a handout

### ISSUE THREAD

**Issue by tvladeck** [rstudio/tufte#37]
Here is a minimal reprex: (Excuse the `\` before the backticks marking the chunks, I couldn't figure out how to escape them inside the issue)

I used `xelatex` because that was in the template file in `RStudio` but it doesn't work without it either. 

```
---
title: "Test"
output:
  tufte::tufte_handout:
    latex_engine: xelatex
---

\```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
\```

\```{r, fig.margin = T}
knitr::kable(
  mtcars[1:6, 1:6], caption = 'A subset of mtcars.'
)
\```
```

**Comment by josiekre** [comment]
I am experiencing this too. They go in the margin if I switch to 'xtable::xtable()' and add results='asis', but I prefer to leave it as kable().

**Comment by yihui** [comment]
Setting `knitr::opts_knit$set(kable.force.latex = TRUE)` might solve the problem.

**Comment by tvladeck** [comment]
It works for the simple reprex, but in my more complicated example I get the following error when I do that:

`! LaTeX Error: Environment longtable undefined.`

**Comment by yihui** [comment]
@tvladeck You may add `tables: yes` (as a _top-level_ option) to YAML, or add `\usepackage{longtable}` to the LaTeX preamble.

**Comment by tvladeck** [comment]
ah yes, this works for me! should I close the issue?

**Comment by yihui** [comment]
If will be better if you could send a pull request after updating the example document: https://github.com/rstudio/tufte/blob/master/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd

**Comment by aminadibi** [comment]
@yihui Setting `knitr::opts_knit$set(kable.force.latex = TRUE)` does move the caption to the margin in the pdf, but also messes with the gridlines:
![image](https://user-images.githubusercontent.com/20497354/35708226-fad91834-0761-11e8-86b2-5ba62c8bc0a1.png)
