### ISSUE TITLE
How can I use translations for reserved words (i.e. figure, table, bibliography etc.)

### ISSUE THREAD

**Issue by ilkerarslan** [rstudio/tufte#38]
> I am writing a document in RStudio / Rmarkdown / Tufte style. The document is in Turkish. I want to use Turkish translations for the words like "Figure, Table" and others. 

Could you please help me?

**Comment by yihui** [comment]
@eliocamp It is equivalent to setting `lang: tk` in the YAML metadata as a top-level option. But I doubt if this really works magically. It probably works for LaTeX output, but I'm sure it won't work for HTML output. @ilkerarslan didn't mention the specific output format.

**Comment by eliocamp** [comment]
Sorry, I didn't know about `lang` as a top-level option. Thanks.

**Comment by ilkerarslan** [comment]
Sorry, I just saw the comments. Many thanks. That was helpful. Just instead of tk it is tr :). 

Regards,
