### ISSUE TITLE
Full-width table

### ISSUE THREAD

**Issue by josiekre** [rstudio/tufte#39]
Is there a way to produce a full-width table? 

According to the [tufte_book LaTeX documentation](http://www.latextemplates.com/templates/books/1/book_1_documentation.pdf), this would be implemented with a `table*` environment rather than `table` (page 23). I see how to do the full-width figure (`fig.fullwidth = TRUE`), but cannot see the table equivalent.

**Comment by yihui** [comment]
Not tested, but my guess: with https://github.com/rstudio/tufte/issues/37#issuecomment-300971548 and `kable(..., table.envir = 'table*')` should make it.

**Comment by josiekre** [comment]
That worked to get the table full width. However, the caption overlaps with the table. I tried this for a couple different tables spaced throughout the page and same thing. Any ideas where to look to fix that?

Also, what about for tufte_html?  Is that possible?

![screenshot 2017-05-16 11 48 46](https://cloud.githubusercontent.com/assets/5776153/26115353/c27eed80-3a2d-11e7-98cf-b6cd59fd10ff.png)

**Comment by yihui** [comment]
I'm not sure. Perhaps `keep_tex: true` and look at the .tex source?

This is not possible for HTML output. 

Usually the support for tables has fairly low priority in my agenda. It is not easy to do well, and tables can be so much more complicated than graphics.

**Comment by RSchwinn** [comment]
Another life saver. Thank you Yihui. You are the best.

**Comment by yihui** [comment]
With the latest version of **tufte** on CRAN (v0.6) and a recent version of RStudio (which has a more recent version of Pandoc), you can generate a full width table for both LaTeX and PDF output. Example:

````md
---
title: Tufte document
output:
  tufte::tufte_handout: default
  tufte::tufte_html: default
---

```{css, echo=FALSE}
div.fullwidth > table {
  width: 100%;
}
```

Hello world... Hello world... Hello world... Hello world... Hello world...
 Hello world... Hello world... 

::: {.fullwidth}
```{r}
knitr::kable(head(mtcars), table.envir = 'table*')
```
:::
````

![tufte html output](https://user-images.githubusercontent.com/163582/81422053-140f2180-9118-11ea-814c-275f5ab5987f.png)

![tufte latex output](https://user-images.githubusercontent.com/163582/81422315-6a7c6000-9118-11ea-8714-7ff9d9a6336c.png)
