### ISSUE TITLE
Escaping backticks in r inline code to call margin_note

### ISSUE THREAD

**Issue by puterleat** [rstudio/tufte#42]
If I write the following inline within rmarkdown:
```
`r tufte::margin_note('To find a list of all the built in datasets you can type `help(datasets)`')`
```

I get the following error:

```
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:20: unexpected INCOMPLETE_STRING
1: tufte::margin_note('To find a list of all the built in datasets you can type 
                       ^
```

The problem is that the normal scale of `\` doesn't seem to work. Nor adding multiple backticks. The only solution I came to is:

```
`r tufte::margin_note('To find a list of all the built in datasets you can type \x60help(datasets)\x60')`
```

Which feels like a real hack. Is this the only way of doing it?

**Comment by puterleat** [comment]
Just to clarify - it's the backticks in the quoted text causing the issue...

**Comment by yihui** [comment]
Yes, it is the only way.

**Comment by puterleat** [comment]
Is this a bug in margin_note, or in the parsing of inline R in rmarkdown?

**Comment by yihui** [comment]
The latter. It is not a bug, though. It is by design. It is hard to tell if a backtick means to end an inline expression or just a literal backtick.
