### ISSUE TITLE
\subsubsection is undefined by this class

### ISSUE THREAD

**Issue by zeigerpuppy** [rstudio/tufte#44]
Looks like it's not possible to use subsubsections, like

```md
## Subsection

### Subsubsection
```

This would be good to handle without an error as it will pretty commonly be used

**Comment by yihui** [comment]
Edward Tufte discourages using section levels that are too deep. If you do not appreciate his design philosophy, perhaps this style is not a good choice to you.

**Comment by yihui** [comment]
Duplicate of #34
