### ISSUE TITLE
No date in tufte-handout

### ISSUE THREAD

**Issue by dshuman1** [rstudio/tufte#45]
When the date is left blank in the RMarkdown file, it still appears in the compiled handout pdf. I fixed this problem by replacing

$if(date)$
\date{$date$}
$endif$

with this 

$if(date)$
\date{$date$}
$else$
\date{}
$endif$

in tufte-handout.tex

**Comment by yihui** [comment]
Please feel free to submit a pull request to fix this. Thanks!

**Comment by dshuman1** [comment]
OK, thanks. I will try to do that. I’m relatively new to GitHub. 

Any chance you’d considering adding additional theorem environments to the default bookdown package? It would be really nice to have Exercise (behaving like Definition) and Solution (behaving like Proof). I’m trying to add them manually in my preamble (not successful yet, but feel like I’m not too far away), but I suspect others writing textbooks and activities would like to have those options.

Your packages are great! Thanks for sharing with the community.

—————————--------------------------------------------------------------------
David Shuman
Assistant Professor
Department of Mathematics, Statistics, and Computer Science
Macalester College
Olin-Rice Science Center, Room 228
651-696-6029
dshuman1@macalester.edu
http://www.macalester.edu/~dshuman1/
--------------------------------------------------------------------------------------

**Comment by dshuman1** [comment]
Sorry, I just saw that you prefer to have suggestions posted directly on GitHub, so I will post there! Thanks again.

**Comment by yihui** [comment]
Actually #9 has fixed this issue two years ago.
