### ISSUE TITLE
Image (.png/.jpg/...) in margin

### ISSUE THREAD

**Issue by KleinhansDa** [rstudio/tufte#50]
Hello,

First, thanks for the great package. 
I have a problem showing images in the margin.
If I use "![image](Path)" it is shown in the main block, but if I wrap it in "{marginfigure}" it doesn't work anymore.

How do I do this?

PS: I want to compile it to .pdf

**Comment by yulijia** [comment]
```
\begin{marginfigure}
\includegraphics[width=\linewidth]{./Desktop/bug.png} 
\end{marginfigure}
```
you can write LaTeX in rmarkdown file
