### ISSUE TITLE
Sidenotes placed at the bottom instead at the side

### ISSUE THREAD

**Issue by peetCreative** [rstudio/tufte#51]
I just started writing some Work using Rmarkdown.
Somehow on my maschine the placements of "Footnotes" on the side does not work.
Installed all packages. Just tried the example.
However this is a reduced example.
Of course I replace ´ with \`
```
---
title: "Test"
subtitle: "More Test"
author: "Someone"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
link-citations: yes
---
´´´
{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
´´´

# Introduction
This style has been implemented in LaTeX and HTML/CSS^[See Github repositories [tufte-latex](https://github.com/tufte-latex/tufte-latex) and [tufte-css](https://github.com/edwardtufte/tufte-css)], respectively. 
```

![screenshot_20171210_195305](https://user-images.githubusercontent.com/5854864/33808288-072ddcde-dde4-11e7-9f8f-150e58e5111f.png)

**Comment by yihui** [comment]
Please provide `devtools::session_info('tufte')` and `rmarkdown::pandoc_version()`. If you happen to have installed Pandoc 2.0 by yourself, please read https://yihui.name/en/2017/11/pandoc-2/.

**Comment by peetCreative** [comment]
I have installed pandoc-citeproc through package manager on my arch my self as I remember. 
However I read the linked article and I'm not sure, what is actually wrong.
So I'll try to downgrade pandoc for now.
`
> devtools::session_info('tufte')
Session info ------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language en_US:de:ru                 
 collate  de_DE.UTF-8                 
 tz       Europe/Stockholm            
 date     2017-12-10                  

Packages ----------------------------------------------------------
 package   * version date       source         
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2) 
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.2) 
 digest      0.6.12  2017-01-27 CRAN (R 3.4.2) 
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.2) 
 graphics  * 3.4.3   2017-11-30 local          
 grDevices * 3.4.3   2017-11-30 local          
 highr       0.6     2016-05-09 CRAN (R 3.4.2) 
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.2) 
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.2) 
 knitr       1.17    2017-08-10 CRAN (R 3.4.2) 
 magrittr    1.5     2014-11-22 CRAN (R 3.4.2) 
 markdown    0.8     2017-04-20 CRAN (R 3.4.2) 
 methods   * 3.4.3   2017-11-30 local          
 mime        0.5     2016-07-07 CRAN (R 3.4.2) 
 Rcpp        0.12.14 2017-11-23 cran (@0.12.14)
 rmarkdown   1.8     2017-11-17 CRAN (R 3.4.2) 
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.2) 
 stats     * 3.4.3   2017-11-30 local          
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2) 
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.2) 
 tools       3.4.3   2017-11-30 local          
 tufte       0.2     2016-02-07 CRAN (R 3.4.3) 
 utils     * 3.4.3   2017-11-30 local          
 yaml        2.1.15  2017-12-01 CRAN (R 3.4.3) 
> rmarkdown::pandoc_version()
[1] ‘2.0.4’
`

**Comment by yihui** [comment]
Pandoc 2.0 is not supported in this package at the moment. Since you use RStudio, you can simply remove the pandoc package you installed.

**Comment by yihui** [comment]
This particular should be fixed now, but there are still other issues with Pandoc 2.0, which I'm still investigating. Thanks for the report!
