### ISSUE TITLE
Not compatible with Pandoc 2.0

### ISSUE THREAD

**Issue by yihui** [rstudio/tufte#52]
I don't know why (yet).

**Comment by jtth** [comment]
I can't seem to get it to work b/c of the "chapters" issue. Is that it? If not, how do I fix that? 

`--chapters has been removed. Use --top-level-division=chapter instead.`

**Comment by yihui** [comment]
@jtth Good catch! Just fixed it. Thanks!

**Comment by jtth** [comment]
Works perfectly now. Thank *you*!
