### ISSUE TITLE
Error: pandoc document conversion failed with error 5

### ISSUE THREAD

**Issue by statsandthings** [rstudio/tufte#56]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows 7 Professional
    R Version       : 3.4.4
    rmarkdown       : 1.9
    knitr           : 1.20
    tufte           : 0.3
    pandoc          : 2.1.3

### Steps to reproduce the problem
Knit to `tufte_book` the following tufte default template, as a pdf. It won't knit and instead I get an *"Error: pandoc document conversion failed with error 5"*. I have reinstalled R Studio, updated to R 3.4.4 and updated all my packages with `update.packages()`.

I am able to knit the default *tufte_template* to HTML without issue. When I do the tufte_book to pdf is when I get that error.

**[Edit]** Updated to the dev version of tufte and cleaned up my code. Now I get the error *Error in tools::file_path_as_absolute(output_file) : file 'tufte_book.pdf' does not exist*.

````
---
title: "Tufte Handout"
subtitle: "An implementation in R Markdown"
author: "JJ Allaire and Yihui Xie"
date: "`r Sys.Date()`"
output:
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Introduction

The Tufte handout style is a style that Edward Tufte uses in his books and handouts. Tufte's style is known for its extensive use of sidenotes, tight integration of graphics with text, and well-set typography. This style has been implemented in LaTeX and HTML/CSS^[See Github repositories [tufte-latex](https://github.com/tufte-latex/tufte-latex) and [tufte-css](https://github.com/edwardtufte/tufte-css)], respectively. We have ported both implementations into the [**tufte** package](https://github.com/rstudio/tufte). If you want LaTeX/PDF output, you may use the `tufte_handout` format for handouts, and `tufte_book` for books. For HTML output, use `tufte_html`. These formats can be either specified in the YAML metadata at the beginning of an R Markdown document (see an example below), or passed to the `rmarkdown::render()` function. See @R-rmarkdown more information about **rmarkdown**.

```yaml
---
title: "An Example Using the Tufte Style"
author: "John Smith"
output:
  tufte::tufte_handout: default
  tufte::tufte_html: default
---
```

There are two goals of this package:

1. To produce both PDF and HTML output with similar styles from the same R Markdown document;
1. To provide simple syntax to write elements of the Tufte style such as side notes and margin figures, e.g. when you want a margin figure, all you need to do is the chunk option `fig.margin = TRUE`, and we will take care of the details for you, so you never need to think about `\begin{marginfigure} \end{marginfigure}` or `<span class="marginfigure"> </span>`; the LaTeX and HTML code under the hood may be complicated, but you never need to learn or write such code.

If you have any feature requests or find bugs in **tufte**, please do not hesitate to file them to https://github.com/rstudio/tufte/issues. For general questions, you may ask them on StackOverflow: http://stackoverflow.com/tags/rmarkdown.
````

**Comment by yihui** [comment]
Please try the development version first:

```r
devtools::install_github('rstudio/tufte')
```

**Comment by yihui** [comment]
BTW, next time please use the syntax for code blocks to post examples ([four backticks](https://yihui.name/en/2017/05/four-backticks-github/))), instead of quotes (`>`). And please [make your example minimal](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) if possible.

**Comment by statsandthings** [comment]
I didn't know I could use four backticks. I was using three backticks and everything looked goofy. Thanks for that tip. I've cleaned up the code and also made it minimal.

I just updated to the dev version of tufte, and am still able to knit an html, but now when I knit to tufte_book (pdf) I get this error *Error in tools::file_path_as_absolute(output_file) : file 'tufte_book.pdf' does not exist*.

**Comment by yihui** [comment]
How about `install.packages('tinytex')`? Hopefully that should tell you more information about the failure. If not, what is your LaTeX distribution? If it is MiKTeX, you may try TinyTeX instead:

```r
tinytex::install_tinytex()
```

**Comment by statsandthings** [comment]
Yes, I am using MiKTeX. I just tried `install.packages('tinytex')`, ran `library(tinytex)` in my console, and added `library(tinytex)` to the first chunk of the rmarkdown document, one line below `library(tufte)`. This is the complete error I get after *saving* and choosing "Knit to tufte_book" from R Studio:

> Output created: tufte_book.pdf
> Error in tools::file_path_as_absolute(output_file) : 
>   file 'tufte_book.pdf' does not exist
> Calls: <Anonymous> -> <Anonymous>
> In addition: Warning message:
> running command '"xelatex" -halt-on-error -interaction=batchmode "tufte_book.tex"' had status 1 
> Execution halted

I should also mention I can't get this to work on my Ubuntu 16.04 Linux box which uses TeX Live. But we won't worry about that now.

**Comment by yihui** [comment]
Then please try `tinytex::install_tinytex()` as I suggested above.

**Comment by statsandthings** [comment]
For a myriad of reasons I need to stick with MikTeX. @imanuelcostigan do you want to try this solution `tinytex::install_tinytex()`?

**Comment by yihui** [comment]
With `tinytex::install_tinytex()`, everything will be automated; with MiKTeX, you have to be a LaTeX expert to figure out the reason for the failure.

**Comment by statsandthings** [comment]
I can't do it on my *production* Windows box, but I can try this out on my *play* Windows box. It will be a little while before I'm back in front of it, and then I'll try out `tinytex::install_tinytex()`. The tufte package is really cool so I'd like to see it working.

**Comment by yihui** [comment]
Fair enough. Without seeing the detailed error log, my wild guess is that you probably didn't have the `tufte-latex` package installed in MiKTeX, or perhaps there are other missing LaTeX packages.

**Comment by statsandthings** [comment]
I did a `knit to tufte_book` on my other Windows box, and I was able to knit the pdf. Weird. I think they have the same versions of all R packages, Pandoc, R, R Studio, etc. but I must be mistaken. I am using the latest version of Pandoc and I remember reading somewhere this could be problematic. I am now using the development version of tufte-book on all machines. The one difference I can think of is one machine is Windows 7 and one is Windows 10.

I should paste the output below. It looks like there is way too much white space. Is this intentional? When I export to html the document is one continuous piece. Look at the boxplot. There's a ton of whitespace above and below the boxplot. And then there's an additional blank page. Since there's no errors is it still a good idea to install tinytex to help you troubleshoot?

![Alt Text](https://i.imgur.com/4Aop2NX.png)

**Comment by imanuelcostigan** [comment]
I am getting this error using ioslides not tufte on both 3.4.4 and 3.5.0 and latest packages from CRAN. My session info:
````
Session info ----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32             
 ui       RStudio (1.2.594)           
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2018-05-01                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 backports   1.1.2   2017-12-13 CRAN (R 3.5.0)
 base      * 3.5.0   2018-04-23 local         
 compiler    3.5.0   2018-04-23 local         
 datasets  * 3.5.0   2018-04-23 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.5.0)
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)
 evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)
 graphics  * 3.5.0   2018-04-23 local         
 grDevices * 3.5.0   2018-04-23 local         
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
 knitr       1.20    2018-02-20 CRAN (R 3.5.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
 memoise     1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods   * 3.5.0   2018-04-23 local         
 Rcpp        0.12.16 2018-03-13 CRAN (R 3.5.0)
 rmarkdown   1.9     2018-03-01 CRAN (R 3.5.0)
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)
 stats     * 3.5.0   2018-04-23 local         
 stringi     1.1.7   2018-03-12 CRAN (R 3.5.0)
 stringr     1.3.0   2018-02-19 CRAN (R 3.5.0)
 tools       3.5.0   2018-04-23 local         
 utils     * 3.5.0   2018-04-23 local         
 withr       2.1.2   2018-03-15 CRAN (R 3.5.0)
 yaml        2.1.18  2018-03-08 CRAN (R 3.5.0)
````

My test Rmd file is the default one created in RStudio's New File menu:

````
---
title: "Test"
author: "My name"
date: "01/05/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

````

**Comment by statsandthings** [comment]
I went on to my Linux Ubuntu 16.04 machine and removed TexLive using these commands:
```
sudo apt-get purge texlive*
sudo rm -rf /usr/local/texlive/* and rm -rf ~/.texlive*
sudo rm -rf /usr/local/share/texmf
sudo rm -rf /var/lib/texmf
sudo rm -rf /etc/texmf
sudo apt-get remove tex-common --purge
rm -rf ~/.texlive
find -L /usr/local/bin/ -lname /usr/local/texlive/*/bin/* | xargs r
```

I then installed TinyTeX with `install_tinytex(force = TRUE)` because I was getting this error `Error: Detected an existing tlmgr at /home/statsandthings/bin/tlmgr.` when doing the standard `install_tinytex()`.

Now when I try to knit_to_tufte_book I get this error.
```
--chapters has been removed. Use --top-level-division=chapter instead.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Execution halted
```
