### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by instantkaffee** [rstudio/tufte#6]
Using toc: TRUE in the YAML seems not to work.

**Comment by yihui** [comment]
Please show it by a minimal reproducible example (below is mine that works perfectly well). It is hard to fix anything that "_seems_" to be a bug. Thanks!

    ---
    title: "Tufte Handout"
    output:
      tufte::tufte_html: 
        toc: TRUE
    ---
    
    # Introduction
    
    The Tufte handout style

**Comment by instantkaffee** [comment]
Thx, works perfectly.
