### ISSUE TITLE
Footnote in bullet list renders in margin, but with wrong margin 

### ISSUE THREAD

**Issue by haakonstorm** [rstudio/tufte#63]
Example Rmarkdown in tufte html:

```
* Test test
* A-GPS^[*Assisted-GPS*] circuitry and sky-facing antennae
* test test 
```

Document knits OK, Footnote is rendered in the margin, but the margin is not aligned with the margin over and below. 

(Rstudio 1.2, all packages updated to newest versions, macOS 10.14.1).

(BTW: Thanks a lot for all the great work on various aspects of everything R-related! <3)

**Comment by mschilli87** [comment]
I can confirm this issue on Linux with several versions (since I started usung `tufte`).

Here is a full minimal example to show the issue:

````rmd
---
output: tufte::tufte_html
---

some text with sitenote^[regular sitenote] before the list

* list item with sitenote^[list sitenote - shifted agains regular ones]

some text with sitenote^[regular sitenote again - aligned with first one] after the list
````

**Comment by jessekps** [comment]
I use the following workaround, hope it helps

`<style>
li span.sidenote{
  width:61.11%;
  margin-right: -85%;
}
</style>`

**Comment by haakonstorm** [comment]
Clean up, hope it's ok I'm closing this. Jessekps workaround above worked beautifully last time I wrote Rmarkdown. The Tufte style of writing and the Rmarkdown way of distributing reproducible research, combined, is pure gold in my eyes. Thank you all for the great work on this.

**Comment by mschilli87** [comment]
@haakonstorm: Do you have an example how to do this if one needs PDF and HTML output?

**Comment by haakonstorm** [comment]
@mschilli87 I have only ever written 1 Rmarkdown document, which was in an introductory R and biological data analysis course in university. Uni liked it, and are actually showcasing it, here: http://arken.nmbu.no/~jonvi/STIN100_Heen.html

You can have the source, if you want to try and deschiffer my R spaghetti code :)

**Comment by jessekps** [comment]
your example seems to run fine in pdf, no workaround needed.

**Comment by mschilli87** [comment]
@jessekps: It does work fine in PDF, but not in HTML.
You shared a workaround that fixes the issue in HTML, but uses actual HTML code in the source document to so.
So if I need both outputs from the same document, I'd need to apply the workaround when rendering to HTML but not when rendering to PDF. Or am I missing something obvious here?

**Comment by jessekps** [comment]
I was not aware that you can output both formats simultaneously. If that's the case, this will work (it has no effect in pdf but has the same effect as the above snippet in html)
<pre>
```{css, echo=FALSE}
li span.sidenote{ width:61.11%; margin-right: -85%; }
```
</pre>

**Comment by jessekps** [comment]
that being said, the direct <style) tag also seems to be ignored in tufte_handout, so no difference, they both work as far as I can see
