### ISSUE TITLE
Remove background colour in PDF output

### ISSUE THREAD

**Issue by Irshaadv** [rstudio/tufte#65]
Hello everyone, 

Does anyone know how to remove the yellow tint in PDF output? (Or even better, to PDF output the envisioned variant). 

Thanks!
Irshaad

**Comment by yihui** [comment]
I don't see any background color: [Untitled.pdf](https://github.com/rstudio/tufte/files/3163934/Untitled.pdf)

Could you provide a reproducible example and its PDF output? It might be due to your PDF viewer.

**Comment by Irshaadv** [comment]
Oh dear! Perhaps I was imagining the yelllow tint. (because of the HTML output). Really so sorry to have wasted your time. My eyes tricked me.

**Comment by yihui** [comment]
No worries! :)
