### ISSUE TITLE
formal argument "extra_dependencies" matched by multiple actual arguments

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/tufte#7]
Getting:

>Error in html_document_base(smart = smart, theme = theme, self_contained = self_contained,  : 
  formal argument "extra_dependencies" matched by multiple actual arguments
Calls: <Anonymous> ... html_document2 -> <Anonymous> -> output_format -> html_document_base
Execution halted

when trying to use `tufte::tufte_html: default`. It broke on a larger document but it also broke on this smaller snippet:

    ---
    title: "Tufte Handout"
    subtitle: "An implementation in R Markdown"
    author: "JJ Allaire and Yihui Xie"
    date: "`r Sys.Date()`"
    output:
      tufte::tufte_html: default
    ---

    ```{r setup, include=FALSE}
    library(tufte)
    knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
    options(htmltools.dir.version = FALSE)
    ```

    test

I even tried the github versions of `rmarkdown` and `tufte`.

    Session info -----------------------------------------------------------------
     setting  value                       
     version  R version 3.2.3 (2015-12-10)
     system   x86_64, darwin13.4.0        
     ui       RStudio (0.99.862)          
     language (EN)                        
     collate  en_US.UTF-8                 
     tz       America/New_York            
     date     2016-01-24                  

    Packages ---------------------------------------------------------------------
     package   * version  date       source                            
     devtools  * 1.9.1    2015-09-11 CRAN (R 3.2.0)                    
     digest      0.6.9    2016-01-08 CRAN (R 3.2.3)                    
     htmltools   0.3      2015-12-29 CRAN (R 3.2.3)                    
     knitr     * 1.12.3   2016-01-22 CRAN (R 3.2.3)                    
     memoise     0.2.1    2014-04-22 CRAN (R 3.2.0)                    
     rmarkdown * 0.9.5    2016-01-25 Github (rstudio/rmarkdown@fda019a)
     rsconnect   0.4.1.11 2016-01-06 Github (rstudio/rsconnect@3034ab8)
     tufte     * 0.1.1    2016-01-25 Github (rstudio/tufte@7ad0b6b)    
     yaml        2.1.13   2014-06-12 CRAN (R 3.2.0)      

I'm probably doing  something wrong/broke something, but I'm not sure what.

**Comment by yihui** [comment]
This should not be a problem with the CRAN version of rmarkdown, and I just fixed the issue in the development version of rmarkdown. Thanks!

**Comment by hrbrmstr** [comment]
Many thanks for this. It's working _perfectly_ now.
