### ISSUE TITLE
pandoc-citeproc problem

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/tufte#8]
I just tried the knitting the example source from https://github.com/rstudio/tufte/raw/master/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd

It did not work, I get the following error

pandoc-citeproc: When expecting a product of 2 values, encountered an Array of 3 elements instead
pandoc: Error running filter /usr/local/bin/pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83

I also installed the latest version of rmarkdown from github instead of the one from CRAN, but the error remained.

**Comment by neuwirthe** [comment]
Problem solved. I had pandoc installed via brew on OSX. It seems it was an older version. After uninstalling it, rmarkdown used its own version and then things worked.

**Comment by yihui** [comment]
Great. I just submitted a new version of tufte to CRAN last night, and I'm glad I didn't miss a potential issue.
