### ISSUE TITLE
formatR is required for a default tufte document

### ISSUE THREAD

**Issue by cderv** [rstudio/tufte#90]
We have `tidy = TRUE` as option in 
https://github.com/rstudio/tufte/blob/1e6ffd349f632fe622c423b8d1a4db251e06b2df/R/handout.R#L67

This requires the `formatR` package which is not in import. 

This is not a issue we've seen often because skeleton sets it to FALSE
https://github.com/rstudio/tufte/blob/41757912e839642b9bd4a96474ccd39e9f9c10af/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd#L22

I encountered this as a warning in **rmarkdown** tests
https://github.com/rstudio/rmarkdown/pull/1958/checks?check_run_id=1442968802#step:14:34
and it took me time to understand it came from here.

@yihui it is safe to add `formatR` to import, but a cleaner solution would be to set by default tidy option to FALSE. But it has been like that since the start (https://github.com/rstudio/tufte/commit/ea56b52be09e2c5010de3ec6a20856d38368f4a6 and https://github.com/rstudio/tufte/commit/01a4f0a0a7d7dc1c7e3193a9628e5645a68fd85a)

Why set to TRUE if FALSE in skeleton ?

Which solution do you prefer ?

**Comment by cderv** [comment]
In fact even with the default template, if **formatR** is not installed, we get the warning
```
Warning messages:
1: In block_exec(params) : Failed to tidy R code in chunk 'setup'. Reason:
Error in loadNamespace(name) : there is no package called 'formatR'
```

That is unfortunate.

**Comment by yihui** [comment]
I'm okay with removing the setting, which means using the default `tidy = FALSE`. Feel free to commit to the master branch with a news item. Thanks!
