### ISSUE TITLE
Issue with reference parsing with Pandoc 2.11+ when multiple reference in same line

### ISSUE THREAD

**Issue by cderv** [rstudio/tufte#91]
This is from https://community.rstudio.com/t/rstudio-ide-1-4-and-pandoc-completely-freezes/93792/8

In the skeleton file created using the package template, add this 
```
See @R-rmarkdown for more information about **rmarkdown** and also @rmarkdown2018.
```
instead of 
```
See @R-rmarkdown for more information about **rmarkdown**
```
in order to have 2 references in the same html line. 

This will not be parsed correctly by `margin_references` and the first reference will be used twice. 

I believe the issue is with `regexec()` + `regmatches()` - `stringr::str_match_all()` find everything.

**Comment by cderv** [comment]
This follows changes in https://github.com/cderv/tufte/commit/52aaff5b8bf23391fd50f6731b0a48d0c4a76351

**Comment by cderv** [comment]
There was an issue with APA style because the CSL processed by citeproc in Pandoc will add some more attributes to the div of id #refs. Fixed in 43ac801a32201f27379b06881e78d3fb2f8bc3aa

Reported in the community: https://community.rstudio.com/t/rstudio-ide-1-4-and-pandoc-completely-freezes/93792/16

**Comment by mfansler** [comment]
When will this fix be pushed to CRAN? Is there something else holding up a 0.9.1 release?

**Comment by yihui** [comment]
@mfansler I can make the release in the next few days.

**Comment by yihui** [comment]
On CRAN now.

**Comment by mfansler** [comment]
@yihui thank you 🙏 ♥️
